### ISSUE TITLE
Set up the initial structure and configuration for the Mobile Money SDK project.

### ISSUE THREAD

**Issue by benessilfie** [Slightly-Techie/mtn-momo-sdk-go#1]
**Tasks:**

- [x] Initialize Go Module
- [x] Create Directory Structure
- [x] Add any Essential Files
